"""Reconciliation: bind classified documents to generated requirements.

Matches a listing file's documents against each requirement rule's
``satisfied_by.document_types`` list, records an ``Evidence`` row per
(requirement, document) pair, and moves matched requirements
``PENDING -> RECEIVED``.  The matching data lives on the rule, not in
code — see ``app/services/requirement_catalog.py``.

V0 boundaries (deliberate):
- No confidence threshold here: classification confidence is *recorded*
  on ``Evidence`` and gates ``VERIFIED`` in a later slice.  ``verified``
  stays False — verification belongs to rule-check / human review.
- Only ``PENDING`` moves, and only to ``RECEIVED``.  ``RECEIVED`` and
  ``VERIFIED`` merely gain evidence; ``EXCEPTION`` is a human flag and is
  never auto-cleared by a new upload.
- ``UNKNOWN`` documents are excluded before matching: they can never
  satisfy a requirement (they route to review instead, per the Slice 3
  classifier).  They are still reported in ``unmatched_document_ids`` so
  the caller can route them to review — they simply never create
  evidence.
- Idempotency is code-checked: an existing ``(requirement_id,
  document_id)`` pair never gets a second ``Evidence`` row, so a re-run
  creates nothing.  No migration needed for this slice.
- Generation is the caller's job (pipeline wiring, Slice 7).  A file with
  no requirements reconciles to an empty result; this module never
  creates requirements.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from sqlalchemy.orm import Session

from app.db.models import Document, Evidence, ListingFile, Requirement, RequirementRule
from app.domain.enums import DocumentType, EvidenceSource, RequirementState

#: Never matches: unknown classification routes to human review.
UNKNOWN_DOCUMENT_TYPE = DocumentType.UNKNOWN.value


@dataclass(frozen=True)
class ReconciliationResult:
    """What one reconciliation pass did, and what it left unsatisfied."""

    evidence_created: int = 0
    requirements_moved_to_received: list[str] = field(default_factory=list)
    unmet_requirement_keys: list[str] = field(default_factory=list)
    unmatched_document_ids: list[int] = field(default_factory=list)


def document_type_value(document: Document) -> str:
    """The document's type as a plain string.

    ``document_type`` is a ``String`` column typed as ``DocumentType``, so
    a fresh instance may hold the enum member while a loaded one holds the
    plain string; both must compare against the rule's stored type names.
    """
    document_type = document.document_type
    if isinstance(document_type, DocumentType):
        return document_type.value
    return str(document_type)


def satisfied_document_types(rule: RequirementRule) -> frozenset[str]:
    """Document types that satisfy this rule (empty when unspecified)."""
    satisfied_by = rule.satisfied_by or {}
    return frozenset(satisfied_by.get("document_types") or ())


def _load_rules(session: Session, requirements: list[Requirement]) -> dict[int, RequirementRule]:
    rule_ids = {
        requirement.requirement_rule_id
        for requirement in requirements
        if requirement.requirement_rule_id is not None
    }
    if not rule_ids:
        return {}
    rules = session.query(RequirementRule).filter(RequirementRule.id.in_(rule_ids)).all()
    return {rule.id: rule for rule in rules}


def _existing_evidence(
    session: Session, requirements: list[Requirement]
) -> tuple[set[tuple[int, int]], dict[int, int]]:
    """Existing (requirement_id, document_id) pairs and per-requirement row counts."""
    pairs: set[tuple[int, int]] = set()
    counts: dict[int, int] = {}
    rows = (
        session.query(Evidence.requirement_id, Evidence.document_id)
        .filter(Evidence.requirement_id.in_([requirement.id for requirement in requirements]))
        .all()
    )
    for requirement_id, document_id in rows:
        pairs.add((requirement_id, document_id))
        counts[requirement_id] = counts.get(requirement_id, 0) + 1
    return pairs, counts


def reconcile_listing_file(session: Session, listing_file: ListingFile) -> ReconciliationResult:
    """Match the file's documents to its requirements.

    Idempotent: re-running adds no evidence and moves nothing twice.  A
    file with no requirements returns an empty result — requirements are
    generated by ``RequirementEngine``, never here.
    """
    requirements = (
        session.query(Requirement)
        .filter(Requirement.listing_file_id == listing_file.id)
        .order_by(Requirement.id)
        .all()
    )
    if not requirements:
        session.flush()
        return ReconciliationResult()

    documents = (
        session.query(Document)
        .filter(Document.listing_file_id == listing_file.id)
        .order_by(Document.id)
        .all()
    )
    # UNKNOWN never matches; it is reported unmatched instead (review routing).
    matchable = [document for document in documents if document_type_value(document) != UNKNOWN_DOCUMENT_TYPE]

    rules = _load_rules(session, requirements)
    pairs, evidence_counts = _existing_evidence(session, requirements)

    evidence_created = 0
    moved: list[str] = []
    matched_document_ids: set[int] = set()

    for requirement in requirements:
        rule = rules.get(requirement.requirement_rule_id)
        if rule is None:
            continue
        accepted_types = satisfied_document_types(rule)
        if not accepted_types:
            continue
        for document in matchable:
            document_type = document_type_value(document)
            if document_type not in accepted_types:
                continue
            matched_document_ids.add(document.id)
            pair = (requirement.id, document.id)
            if pair in pairs:
                continue
            session.add(
                Evidence(
                    requirement_id=requirement.id,
                    document_id=document.id,
                    source=EvidenceSource.DOCUMENT.value,
                    confidence=document.classification_confidence,
                    verified=False,
                    detail={"document_type": document_type, "matched_via": "satisfied_by"},
                )
            )
            pairs.add(pair)
            evidence_counts[requirement.id] = evidence_counts.get(requirement.id, 0) + 1
            evidence_created += 1
            if requirement.state == RequirementState.PENDING.value:
                requirement.state = RequirementState.RECEIVED.value
                requirement.state_reason = f"Matched document #{document.id} ({document_type})"
                moved.append(requirement.requirement_key)

    session.flush()

    return ReconciliationResult(
        evidence_created=evidence_created,
        requirements_moved_to_received=sorted(moved),
        unmet_requirement_keys=sorted(
            requirement.requirement_key
            for requirement in requirements
            if evidence_counts.get(requirement.id, 0) == 0
        ),
        unmatched_document_ids=sorted(
            document.id for document in documents if document.id not in matched_document_ids
        ),
    )
