from enum import Enum


class BusinessOutcome(str, Enum):
    READY_FOR_PROCESSING = "READY_FOR_PROCESSING"
    PROCESSED = "PROCESSED"
    DUPLICATE = "DUPLICATE"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    FAILED = "FAILED"


class ProcessingStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    PENDING_RETRY = "PENDING_RETRY"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    FINAL_FAILURE = "FINAL_FAILURE"


class WorkItemStatus(str, Enum):
    PENDING = "PENDING"
    CLAIMED = "CLAIMED"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class StageStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    SUCCESS = "SUCCESS"
    RETRYABLE_FAILURE = "RETRYABLE_FAILURE"
    PERMANENT_FAILURE = "PERMANENT_FAILURE"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    FINAL_FAILURE = "FINAL_FAILURE"


class ProcessingStage(str, Enum):
    EMAIL_INGESTION = "EMAIL_INGESTION"
    ATTACHMENT_RETRIEVAL = "ATTACHMENT_RETRIEVAL"
    DOCUMENT_PARSING = "DOCUMENT_PARSING"
    OCR = "OCR"
    CLASSIFICATION = "CLASSIFICATION"
    APPLICABILITY = "APPLICABILITY"
    CUSTOMER_RESOLUTION = "CUSTOMER_RESOLUTION"
    DUPLICATE_DETECTION = "DUPLICATE_DETECTION"
    FIELD_VALIDATION = "FIELD_VALIDATION"
    BUSINESS_DECISION = "BUSINESS_DECISION"
    CRM_ACTION = "CRM_ACTION"
    COMPLETE = "COMPLETE"


class FailureType(str, Enum):
    RETRYABLE = "RETRYABLE"
    PERMANENT = "PERMANENT"


class DocumentType(str, Enum):
    INVOICE = "INVOICE"
    REMITTANCE = "REMITTANCE"
    PAYMENT_ADVICE = "PAYMENT_ADVICE"
    CREDIT_NOTE = "CREDIT_NOTE"
    DEBIT_NOTE = "DEBIT_NOTE"
    BANK_STATEMENT = "BANK_STATEMENT"
    UNKNOWN = "UNKNOWN"
    NOT_APPLICABLE = "NOT_APPLICABLE"
